name: Clone and Install Crafty

on:
  workflow_dispatch:

jobs:
  install-crafty:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitLab Repository
        run: |
          git clone https://gitlab.com/crafty-controller/crafty-installer-4.0.git

      - name: Install Crafty
        run: |
          cd crafty-installer-4.0
          yes | sudo ./install_crafty.sh
