name: Clone Actions-Server Repository
on: [push]

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone specific branch of Actions-Server repository
      run: |
        git clone --branch playit-only https://github.com/Briiqn/Actions-Server.git
